### ISSUE TITLE
add support for VM machine types

### ISSUE THREAD

**Issue by ddemlow** [ScaleComputing/HyperCoreAnsibleCollection#12]
i will need to clarify the machine type options available in 9.1 ... bios for sure (and is default) but I believe UEFI is also available even in 9.1  (this is also exposed in UI as boot type when creating VM) 

and when 9.2 is released (and in latest internal build 9.2.5) vTPM+UEFI will also become available

from 9.2. rest api docs 

machineType | stringScale 'Hardware' version. Possible values include:machineTypeDescriptionscale-7.2BIOSscale-8.10UEFIscale-uefi-tpm-9.2vTPM+UEFI (Experiemental) | machineType | Description | scale-7.2 | BIOS | scale-8.10 | UEFI | scale-uefi-tpm-9.2 | vTPM+UEFI (Experiemental)
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

scale-7.2 | BIOS
scale-8.10 | UEFI
scale-uefi-tpm-9.2 | vTPM+UEFI (Experiemental)

there may be some related changes beyond just setting machine type such as the NVRAM virtual disk used to store UEFI config - possibly same for vTPM 
<img width="454" alt="image" src="https://user-images.githubusercontent.com/26821128/192897919-76fb828a-3234-40fc-91d8-a522f308e3aa.png">

**Comment by tjazsch** [comment]
Dave, should `machine type` be a property that you can modify as well (such as `vcpu`, `description`), or just pass when creating the VM?

**Comment by tjazsch** [comment]
If it's OK, I'm already going to include option `vTPM+UEFI` for machine type as well.

**Comment by ddemlow** [comment]
The UI only allows it to be set when VM is created. So that's fine / safest however, the API will allow changes but it's an advanced Action generally only done by support

And yes, including VTPM makes sense now.  I can test that
