### ISSUE TITLE
:rocket: Feature request: add &name value to support_tunnel modules

### ISSUE THREAD

**Issue by ddemlow** [ScaleComputing/HyperCoreAnsibleCollection#205]
## Is your feature request related to a problem? Please describe.
beginning in hypercore 9.2.16 and 9.1.24 changes to support tunnels are logged to cluster log along with the logged in user name where applicable.  

although ansible uses endpoint that does not require auth - it would be desirable to allow module to pass a user name that would be noted in the cluster log for support tunnel opens and closes... this can be done by adding &name="{{ name }}" to end of uri for example - https://clusterip/support-api/close?&name=dave and support-api/open?code=3112&name=dave

example of cluster logging

<img width="979" alt="image" src="https://user-images.githubusercontent.com/26821128/231555564-4015bc87-ac13-423c-8fdd-99c09f4b319c.png">

## Describe the solution you'd like
provide an optional parameter to pass a name

## Additional context

I have tried also including &name= on older versions and appears it is simply ignored there but still takes desired action - so I don't believe any version check would be required

**Comment by justinc1** [comment]
If we add extra parameter, then playbook writer can send arbitrary username. It could be confusing to look at logs, and see 'dave' opened the tunnel, but there is no user 'dave' on that cluster. Maybe we should just use the username that is used to login to cluster, and not have any extra parameter.

**Comment by justinc1** [comment]
Testing on https://10.5.11.50/ - v9.2.16, it seems correct URL is like https://clusterip/support-api/close?&user=dave (not name=dave). I will use the `user=` in code.

@TomboScaleComputing Just to double check - the 9.2.16 version does behave the way you want, the `user=some_user_name` is intentional?
