### ISSUE TITLE
integration test or ci test actions should cleanup replication on target cluster

### ISSUE THREAD

**Issue by ddemlow** [ScaleComputing/HyperCoreAnsibleCollection#25]
deleting a replicated VM by design does NOT delete the VM on the target cluster - so ci testing accumulates VM's on the target cluster.

need to create some automation to clean that up.  

it would be safe to assume that hypercore cluster credentials are the same on replication target cluster - and that it is accessible from ci runner so that replication target VM could be cleaned up automatically... given that should be able to get everything needed to delete VM on the replication target cluster

**Comment by justinc1** [comment]
I agree, we should add this cleanup to CI.

**Comment by justinc1** [comment]
WIP by justin, https://github.com/ScaleComputing/HyperCoreAnsibleCollection/tree/25-cleanup-replication - but was not tested yet.
On gitlab - gitlab CI does not have access to the second cluster , @domendobnikar  - if you run the cleanup playbook manually, then you should be able to check it is functional.
On github - @ddemlow  will need to tell us  URL/username/password of the replication destination cluster, then @justinc1  can enter this into github CI secrets, and it should work.
