### ISSUE TITLE
:lady_beetle: Bug: error in scale_computing.hypercore.version_update_single_node : Wait until VMs shutdown

### ISSUE THREAD

**Issue by ddemlow** [ScaleComputing/HyperCoreAnsibleCollection#257]
## Describe the bug

**To Reproduce**

playbook is pretty simple (full playbook can be provided_

    - name: Update HyperCore single-node system to a desired version
      include_role:
        name: scale_computing.hypercore.version_update_single_node
      vars:
        version_update_single_node_desired_version: "{{ hypercore_desired_version }}"

TASK [scale_computing.hypercore.version_update_single_node : Wait until VMs shutdown] ************************************************************************************************************************
task path: /Users/davedemlow/ansible_collections/scale_computing/hypercore/roles/version_update_single_node/tasks/shutdown_vms.yml:14
Monday 31 July 2023  12:39:50 -0400 (0:00:00.039)       0:00:10.780 *********** 
fatal: [192.168.1.246.nip.io]: FAILED! => {
    "msg": "Unexpected templating type error occurred on ({{ range(0, (version_update_single_node_shutdown_wait_time / 10.0) | round(0, 'ceil') | int) | list }}): unsupported operand type(s) for /: 'str' and 'float'"
}

I am testing against a single node running 9.2.17.211525 from current "main" 

## System Info (please complete the following information):
 - HyperCore Version: 
 - Ansible Version: 
 - Collection Version [e.g. 22]

**Comment by ddemlow** [comment]
the bug seems to be in the default value specified in the role not being a float (here https://github.com/ScaleComputing/HyperCoreAnsibleCollection/blob/main/roles/version_update_single_node/defaults/main.yml)

if I add the following to my playbook it works

  vars: 
    version_update_single_node_shutdown_wait_time: 300

**Comment by justinc1** [comment]
The https://github.com/ScaleComputing/HyperCoreAnsibleCollection/blob/main/roles/version_update_single_node/defaults/main.yml wants to use (deprecated) `scale_computing_hypercore_shutdown_wait_time` as default value for `version_update_single_node_shutdown_wait_time`. Sorry I missed I need to add the extra type conversion in role implementation.
