### ISSUE TITLE
:lady_beetle: Bug: version_update_single_node role isn't waiting for update to actually start up and concluding it's done

### ISSUE THREAD

**Issue by ddemlow** [ScaleComputing/HyperCoreAnsibleCollection#258]
## Describe the bug

**To Reproduce**

https://github.com/ScaleComputing/HyperCoreAnsibleCollection/blob/main/roles/version_update_single_node/tasks/main.yml
needs to wait for update to actually start before initial status check.

probably better solutions available but adding a 60 second wait in my case was sufficient (in some others might need a longer wait or more advanced comparison to tell that update actually is started or at least attempted to start and then terminated)

   # ----------------- UPDATE --------------------

    - name: Update single-node system
      scale_computing.hypercore.version_update:
        icos_version: "{{ version_update_single_node_desired_version }}"
      register: version_update_single_node_update_result

    - name: wait 60 seconds
      wait_for:
        timeout: 60

    - name: Check update status
      ansible.builtin.include_tasks: update_status_check.yml

    - name: Show update result
      ansible.builtin.debug:
        var: version_update_single_node_update_result

## System Info (please complete the following information):
 - HyperCore Version: 
 - Ansible Version: 
 - Collection Version [e.g. 22]

**Comment by justinc1** [comment]
The bug was added with 355e65a6254883da54796665ac063b4c2d78d29c, where we (em, I...) removed the 60 sec delay.

The role is tested only manually, it is hard to find race conditions.

More advanced condition - we could use `version_update_status_info` and look at `record.to_version` output.
