### ISSUE TITLE
 should this ci-infra folder be remove

### ISSUE THREAD

**Issue by ddemlow** [ScaleComputing/HyperCoreAnsibleCollection#26]
should this ci-infra folder be removed (or updated?) from public git repo? https://github.com/ScaleComputing/HyperCoreAnsibleCollection/tree/main/ci-infra

**Comment by justinc1** [comment]
Yes, just not immediately. Directory was added to enable CI testing on XLAB self-hosted gitlab. It still get used, but when I manually push main branch to our XLAB gitlab. There all CI tests pass.

On github the SMB server access still needs some debugging. And we cannot that easily run tests in parallel (github runner limitation).

**Comment by justinc1** [comment]
Directory now contains also:
- Dockerfile used to build docker image for running CI tests
- configuration for chrony NTP daemon, with instruction how ti use it (a readme file; we could convert it to a Dockerfile)

So now we do use this directory.
