### ISSUE TITLE
:rocket: Feature request: Ansible Core 2.13 and AAP 2.2 End of Life

### ISSUE THREAD

**Issue by ddemlow** [ScaleComputing/HyperCoreAnsibleCollection#279]
Ansible Core 2.13 and AAP 2.2 End of Life

Ansible Core 2.13 and Ansible Automation Platform (AAP) 2.2 reached their EoL dates on November 26, 2023.

Please update your collection’s `meta/runtime.yml` file to require at least Ansible Core 2.14.0 and above, so customers know your collection does not support EoL versions of Ansible. 

This meta/runtime.yml change is a gate for certification. Include this change in all collections before releasing on Ansible Automation Hub and update any relevant documentation, such as the “Requirements” section in the collection README.

**Comment by justinc1** [comment]
I will update https://github.com/ScaleComputing/HyperCoreAnsibleCollection/pull/278 . The PR original goal was to test also with ansible-core 2.16, the latest ansible-lint requested to not advertise ansible-core<2.13 as supported.
