### ISSUE TITLE
integration test or ci test actions should cleanup export / import test files on SMB share

### ISSUE THREAD

**Issue by ddemlow** [ScaleComputing/HyperCoreAnsibleCollection#33]
files will accumulate in 3 different directories and subdirectories underneath those

:\integration-test
:\integration-test-vm-export
:\integration-test-vm-import

**Comment by domendobnikar** [comment]
I tried implementing this enhancement without success.
The easiest way would be to use "smbclient" to connect to the SMB with the actual github runner and proceed from there.
There seems to be an issue with access to the SMB. 
I tried multiple different ways to connect, but after looking at logs, looks like the github runner does not have access to the SMB.
My best guess would be that github runner and SMB are not in the same network, resolving into SMB being an unknown name /service.
This is an example of a network interface used by the github runner:
`added interface eth0 ip=172.19.0.2 bcast=172.19.255.255 netmask=255.255.0.0`
These are the errors i'm getting (using github secrets to connect, thus the ***):
```
resolve_hosts: Attempting host lookup for name ***<0x20>
resolve_hosts: getaddrinfo failed for name *** [Name or service not known]
do_connect: Connection to *** failed (Error NT_STATUS_UNSUCCESSFUL)
```
Moving forward my suggestion would be to setup SMB in a way that github runner has access to it, if that is possible.
The only other way of doing this would be to setup an endpoint on the API that would allow deleting files from the SMB.

**Comment by justinc1** [comment]
The github CI runner does not have direct access to this SMB server at all. I forgot on that detail. We cannot do much.

On test cluster for manual testing was SMB server setup on HyperCore VM, so there tests have also direct IP access to SMB server (it is just a VM).

**Comment by domendobnikar** [comment]
The script deletes files that are at least one day old, this way there is no conflict between tests (one deleting files to others when they are still running).
