### ISSUE TITLE
Ansible module documentation error

### ISSUE THREAD

**Issue by jbcreek** [ScaleComputing/HyperCoreAnsibleCollection#336]
## Describe the bug
The documentation for the module plugin, scale_computing.hypercore.api, was malformed. 
1 validation error for ModuleDocSchema
doc -> plugin_name
  extra fields not permitted (type=value_error.extra)

I checked several modules and they all have this issue.

**To Reproduce**
1. Go to '(https://scalecomputing.github.io/HyperCoreAnsibleCollection/collections/scale_computing/hypercore/api_module.html#ansible-collections-scale-computing-hypercore-api-module)'
2. See error

## Expected behavior
Module documentation would be displayed.

## System Info (please complete the following information):
 - HyperCore Version: 
 - Ansible Version: 
 - Collection Version [e.g. 22]

**Comment by shoriminimoe** [comment]
Thank you for reporting this. I rolled back the docs to the previous version until we can correct the errors in the new version.

**Comment by justinc1** [comment]
Thank you @jbcreek for reporting, and @shoriminimoe for rolling back docs. I will look into this in next days.
