### ISSUE TITLE
:lady_beetle: Bug: Passing VCPU via environment variable creates VM with 0 cores

### ISSUE THREAD

**Issue by christianhahnsft22** [ScaleComputing/HyperCoreAnsibleCollection#342]
I'm trying to pass in the number of vcpu via an environment variable like this:

<code>
    - name: Load Number of CPU from environment 
      set_fact:          
        jumphost_cpus: "{{ lookup('env', 'NUMBER_CPU') | int}}"             
   - name: Create VM {{ vm_name }}
      scale_computing.hypercore.vm:
        vm_name: "{{ vm_name }}"
        machine_type: "UEFI"
        memory: "{{ jumphost_ram_size_bytes }}"
        vcpu: "{{ jumphost_cpus | int }}"
</code>
But creating the VM fails with:

fatal: [localhost]: FAILED! => {"changed": false, "msg": "There was a problem during this task execution. Task details: {\"taskTag\": \"316\", \"progressPercent\": 50, \"state\": \"ERROR\", \"formattedDescription\": \"Start Virtual Machine %@\", \"descriptionParameters\": [\"jumphost\"], \"formattedMessage\": \"Cannot start virtual machine 'jumphost'\", \"messageParameters\": [], \"objectUUID\": \"7f742bf2-128e-4f48-883c-0283df4286f3\", \"created\": 1731266925, \"modified\": 1731266937, \"completed\": 1731266937, \"sessionID\": \"a04a8728-932c-4b70-a39d-31b8fbbbe780\", \"nodeUUIDs\": [\"\"]}"}

In the UI I see afterwards a VM which has 0 cores assigned.

**Comment by justinc1** [comment]
Hi. If `NUMBER_CPU` is not set in environ `lookup` will return empty string, and `int` will convert it to number 0. Provide a default value for this case - `jumphost_cpus: "{{ lookup('env', 'NUMBER_CPU') or 2 | int }}"`.

**Comment by justinc1** [comment]
I believe this can be closed. Collection is not causing the problem. Problem origin was how ansible works.
