### ISSUE TITLE
Create / delete named VM snapshot

### ISSUE THREAD

**Issue by ddemlow** [ScaleComputing/HyperCoreAnsibleCollection#39]
As a user I would like to be able to take and delete a named VM snapshot via ansible.

I may for example want to take snapshots before applying VM changes either at hypercore level or inside VM - such as applying updates - and then later delete snapshot after confirming such operation was successful

(See also issue 10 - which would allow cloning from specific named snapshots https://github.com/ScaleComputing/HyperCoreAnsibleCollection/issues/10)

**Comment by ddemlow** [comment]
probably also need way to list snapshots and get info ... so may want vm_snaphot and vm_snapshot_info modules?

**Comment by justinc1** [comment]
Implemented in
- https://github.com/ScaleComputing/HyperCoreAnsibleCollection/pull/217
- https://github.com/ScaleComputing/HyperCoreAnsibleCollection/pull/219
- https://github.com/ScaleComputing/HyperCoreAnsibleCollection/pull/223
- https://github.com/ScaleComputing/HyperCoreAnsibleCollection/pull/233
