### ISSUE TITLE
vm module (possibly others) can't set vcpu to 0

### ISSUE THREAD

**Issue by ddemlow** [ScaleComputing/HyperCoreAnsibleCollection#4]
to prevent a "template" VM such as a cloud image from being accidentally powered on and booted - rendering  it no longer a good template, a workaround has been to set vcpus to 0 using the API ... and then after cloning from the template, set the desired # of vcpu's for the resulting VM.  I attempted to use this approach in the playbook and setting the vcpu to 0 would fail

**Comment by domendobnikar** [comment]
I have tested this with this sample playbook. And I don't seem to be able to reproduce the issue.
`- name: Testing VCPU set to 0
  hosts: localhost
  tasks:
  - name: ubuntu20_04 template - Ubuntu 20.04 - import if not present
    scale_computing.hypercore.vm_import:
      cluster_instance:
          host: 'https://10.5.11.30'
          username: 'admin'
          password: 'admin'
      vm_name: ubuntu20_04
      smb:
        server: "10.5.11.179"
        path: "/users/XLAB-POST-TEST"
        username: example1
        password: badpass
#    ignore_errors: yes
    register: ubuntu20_04

  - name: test vcpu to 0
    scale_computing.hypercore.vm:
      cluster_instance:
          host: 'https://10.5.11.30'
          username: 'admin'
          password: 'admin'
      vm_name: test-vcpu   
      memory: "{{ '1 GB'|human_to_bytes}}"
      description: "blabla"
      tags:
        - Xlab
      vcpu: 0 # filed issue that this can't be set to zero here
      state: present
      power_state: stop
      disks:
      - type: virtio_disk
        disk_slot: 0
        size: "{{ '200 GB' | human_to_bytes }}"
      nics:
      - vlan: 0
        type: virtio
      boot_devices:
      - type: virtio_disk
        disk_slot: 0 

  - name: clone vm test-vcpu - if not present
    scale_computing.hypercore.vm_clone:
      cluster_instance:
          host: 'https://10.5.11.30'
          username: 'admin'
          password: 'admin'
      vm_name: test-vcpu-clone
      tags:
        - Xlab
      source_vm_name: test-vcpu
      cloud_init:
        user_data: |
          #cloud-config
          apt_update: true
          apt_upgrade: true
          password: "BLABLA"
          chpasswd: "BLABLA"
          ssh_pwauth: True
        meta_data: |
          dsmode: local
          network-interfaces: |
            auto lo
            iface lo inet loopback 
            iface ens3 inet static
              address 192.168.1.200
              netmask 255.255.255.0
              gateway 192.168.1.1
              dns-nameservers 8.8.8.8
          local-hostname: demo1

  - name: verify test-vcpu-clone desired configuration  
    scale_computing.hypercore.vm:
      cluster_instance:
          host: 'https://10.5.11.30'
          username: 'admin'
          password: 'admin'
      vm_name: test-vcpu-clone
      memory: "{{ '1 GB'|human_to_bytes}}"
      description: "retesting"
      vcpu: 2
      state: present
      power_state: start   #possible bug - right now the VM doesn't start first time this playbook executes ... it makes some config changes but doesn't start - if you run again it starts
      disks:
      - type: virtio_disk
        disk_slot: 0
        size: "{{ '200 GB' | human_to_bytes }}"
      nics:
      - vlan: 0
        type: virtio
      boot_devices:
      - type: virtio_disk
        disk_slot: 0
`

**Comment by ddemlow** [comment]
just that play run with -vvv - I believe you can see here that vcpu is supposed to be 0 yet is actually 4 and it shows changed=false

davedemlow@C02Z13EYLVDL ansible_collections % ansible-playbook -l staging -t debug Edge_Demo_Playbook.yml -vvv
ansible-playbook [core 2.13.4]
  config file = /Users/davedemlow/ansible_collections/ansible.cfg
  configured module search path = ['/Users/davedemlow/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/davedemlow/ansible_collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.10.6 (main, Aug 11 2022, 13:49:25) [Clang 13.1.6 (clang-1316.0.21.2.5)]
  jinja version = 3.1.2
  libyaml = True
Using /Users/davedemlow/ansible_collections/ansible.cfg as config file
host_list declined parsing /Users/davedemlow/ansible_collections/inventory.yml as it did not pass its verify_file() method
script declined parsing /Users/davedemlow/ansible_collections/inventory.yml as it did not pass its verify_file() method
Parsed /Users/davedemlow/ansible_collections/inventory.yml inventory source with yaml plugin
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: Edge_Demo_Playbook.yml ***************************************************************************************************
1 plays in Edge_Demo_Playbook.yml

PLAY [retail-edge workload deployment playbook] ************************************************************************************
META: ran handlers
<szt15b-01.lab.local> ESTABLISH LOCAL CONNECTION FOR USER: davedemlow
<szt15b-01.lab.local> EXEC /bin/sh -c 'echo ~davedemlow && sleep 0'
<szt15b-01.lab.local> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/davedemlow/.ansible/tmp `"&& mkdir "` echo /Users/davedemlow/.ansible/tmp/ansible-tmp-1664394085.192967-75813-254775107755755 `" && echo ansible-tmp-1664394085.192967-75813-254775107755755="` echo /Users/davedemlow/.ansible/tmp/ansible-tmp-1664394085.192967-75813-254775107755755 `" ) && sleep 0'
<szt15b-01.lab.local> Attempting python interpreter discovery
<szt15b-01.lab.local> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'python3.10'"'"'; command -v '"'"'python3.9'"'"'; command -v '"'"'python3.8'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<szt15b-01.lab.local> Python interpreter discovery fallback (unsupported platform for extended discovery: darwin)
Using module file /Users/davedemlow/ansible_collections/scale_computing/hypercore/plugins/modules/vm.py
<szt15b-01.lab.local> PUT /Users/davedemlow/.ansible/tmp/ansible-local-75810s33gwokd/tmpmpmgxc3p TO /Users/davedemlow/.ansible/tmp/ansible-tmp-1664394085.192967-75813-254775107755755/AnsiballZ_vm.py
<szt15b-01.lab.local> EXEC /bin/sh -c 'chmod u+x /Users/davedemlow/.ansible/tmp/ansible-tmp-1664394085.192967-75813-254775107755755/ /Users/davedemlow/.ansible/tmp/ansible-tmp-1664394085.192967-75813-254775107755755/AnsiballZ_vm.py && sleep 0'
<szt15b-01.lab.local> EXEC /bin/sh -c '/usr/local/bin/python3.10 /Users/davedemlow/.ansible/tmp/ansible-tmp-1664394085.192967-75813-254775107755755/AnsiballZ_vm.py && sleep 0'
<szt15b-01.lab.local> EXEC /bin/sh -c 'rm -f -r /Users/davedemlow/.ansible/tmp/ansible-tmp-1664394085.192967-75813-254775107755755/ > /dev/null 2>&1 && sleep 0'

TASK [protect ubuntu20_04 template from powering on] *******************************************************************************
task path: /Users/davedemlow/ansible_collections/Edge_Demo_Playbook.yml:23
[WARNING]: Platform darwin on host szt15b-01.lab.local is using the discovered Python interpreter at /usr/local/bin/python3.10, but
future installation of another Python interpreter could change the meaning of that path. See https://docs.ansible.com/ansible-
core/2.13/reference_appendices/interpreter_discovery.html for more information.
ok: [szt15b-01.lab.local] => changed=false 
  ansible_facts:
    discovered_interpreter_python: /usr/local/bin/python3.10
  diff:
    after:
      attach_guest_tools_iso: ''
      boot_devices:
      - cache_mode: writethrough
        disable_snapshotting: false
        disk_slot: 0
        iso_name: ''
        mount_points: []
        read_only: false
        size: 214748364800
        tiering_priority_factor: 8
        type: virtio_disk
        uuid: c112578f-ec31-4070-b62b-a841cd169dde
        vm_uuid: 6510aa23-2c9a-4df5-8712-9fe145032103
      description: szt15b-01.lab.local
      disks:
      - cache_mode: writethrough
        disable_snapshotting: false
        disk_slot: 0
        iso_name: ''
        mount_points: []
        read_only: false
        size: 214748364800
        tiering_priority_factor: 8
        type: virtio_disk
        uuid: c112578f-ec31-4070-b62b-a841cd169dde
        vm_uuid: 6510aa23-2c9a-4df5-8712-9fe145032103
      memory: 1073741824
      nics:
      - connected: true
        ipv4_addresses: []
        mac: 7C:4C:58:C8:DB:BD
        type: virtio
        uuid: dc20a239-5851-4fc1-b3d2-c0c63c267073
        vlan: 0
      node_affinity:
        backup_node:
          backplane_ip: ''
          lan_ip: ''
          node_uuid: ''
          peer_id: null
        preferred_node:
          backplane_ip: ''
          lan_ip: ''
          node_uuid: ''
          peer_id: null
        strict_affinity: false
      operating_system: os_other
      power_state: stopped
      snapshot_schedule: ''
      tags:
      - ansible
      - template
      - demo
      uuid: 6510aa23-2c9a-4df5-8712-9fe145032103
      vcpu: 4
      vm_name: ubuntu20_04
    before:
      attach_guest_tools_iso: ''
      boot_devices:
      - cache_mode: writethrough
        disable_snapshotting: false
        disk_slot: 0
        iso_name: ''
        mount_points: []
        read_only: false
        size: 214748364800
        tiering_priority_factor: 8
        type: virtio_disk
        uuid: c112578f-ec31-4070-b62b-a841cd169dde
        vm_uuid: 6510aa23-2c9a-4df5-8712-9fe145032103
      description: szt15b-01.lab.local
      disks:
      - cache_mode: writethrough
        disable_snapshotting: false
        disk_slot: 0
        iso_name: ''
        mount_points: []
        read_only: false
        size: 214748364800
        tiering_priority_factor: 8
        type: virtio_disk
        uuid: c112578f-ec31-4070-b62b-a841cd169dde
        vm_uuid: 6510aa23-2c9a-4df5-8712-9fe145032103
      memory: 1073741824
      nics:
      - connected: true
        ipv4_addresses: []
        mac: 7C:4C:58:C8:DB:BD
        type: virtio
        uuid: dc20a239-5851-4fc1-b3d2-c0c63c267073
        vlan: 0
      node_affinity:
        backup_node:
          backplane_ip: ''
          lan_ip: ''
          node_uuid: ''
          peer_id: null
        preferred_node:
          backplane_ip: ''
          lan_ip: ''
          node_uuid: ''
          peer_id: null
        strict_affinity: false
      operating_system: os_other
      power_state: stopped
      snapshot_schedule: ''
      tags:
      - ansible
      - template
      - demo
      uuid: 6510aa23-2c9a-4df5-8712-9fe145032103
      vcpu: 4
      vm_name: ubuntu20_04
  invocation:
    module_args:
      attach_guest_tools_iso: false
      boot_devices: null
      cloud_init:
        meta_data: null
        user_data: null
      cluster_instance:
        host: https://szt15b-01.lab.local
        password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
        timeout: null
        username: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      description: szt15b-01.lab.local
      disks:
      - cache_mode: null
        disk_slot: 0
        iso_name: null
        size: 214748364800
        type: virtio_disk
      force_reboot: false
      memory: 1073741824
      nics:
      - connected: true
        mac: null
        type: virtio
        vlan: 0
        vm_uuid: 6510aa23-2c9a-4df5-8712-9fe145032103
      power_state: stop
      shutdown_timeout: 300.0
      snapshot_schedule: null
      state: present
      tags:
      - ansible
      - template
      - demo
      **vcpu: 0**
      vm_name: ubuntu20_04
      vm_name_new: null
  record:
  - attach_guest_tools_iso: ''
    boot_devices:
    - cache_mode: writethrough
      disable_snapshotting: false
      disk_slot: 0
      iso_name: ''
      mount_points: []
      read_only: false
      size: 214748364800
      tiering_priority_factor: 8
      type: virtio_disk
      uuid: c112578f-ec31-4070-b62b-a841cd169dde
      vm_uuid: 6510aa23-2c9a-4df5-8712-9fe145032103
    description: szt15b-01.lab.local
    disks:
    - cache_mode: writethrough
      disable_snapshotting: false
      disk_slot: 0
      iso_name: ''
      mount_points: []
      read_only: false
      size: 214748364800
      tiering_priority_factor: 8
      type: virtio_disk
      uuid: c112578f-ec31-4070-b62b-a841cd169dde
      vm_uuid: 6510aa23-2c9a-4df5-8712-9fe145032103
    memory: 1073741824
    nics:
    - connected: true
      ipv4_addresses: []
      mac: 7C:4C:58:C8:DB:BD
      type: virtio
      uuid: dc20a239-5851-4fc1-b3d2-c0c63c267073
      vlan: 0
    node_affinity:
      backup_node:
        backplane_ip: ''
        lan_ip: ''
        node_uuid: ''
        peer_id: null
      preferred_node:
        backplane_ip: ''
        lan_ip: ''
        node_uuid: ''
        peer_id: null
      strict_affinity: false
    operating_system: os_other
    power_state: stopped
    snapshot_schedule: ''
    tags:
    - ansible
    - template
    - demo
    uuid: 6510aa23-2c9a-4df5-8712-9fe145032103
    **vcpu: 4**
    vm_name: ubuntu20_04
  vm_rebooted: false
META: ran handlers
META: ran handlers

PLAY RECAP *************************************************************************************************************************
szt15b-01.lab.local        : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
