### ISSUE TITLE
Rename cloud_init key in post_vm_payload method within VM class inside module_utils

### ISSUE THREAD

**Issue by domendobnikar** [ScaleComputing/HyperCoreAnsibleCollection#41]
cloud_init has the wrong dictionary key in post_vm_payload method during VM creation.
Rename it and write integration + unit tests to check it.

**Comment by justinc1** [comment]
See branches https://github.com/ScaleComputing/HyperCoreAnsibleCollection/tree/41-rename-cloud_init-key-in-post_vm_payload-method-within-vm-class-inside-module_utils, maybe also https://github.com/ScaleComputing/HyperCoreAnsibleCollection/tree/justin-41-rename-cloud_init-key-in-post_vm_payload-method-within-vm-class-inside-module_utils.

**Comment by justinc1** [comment]
After cafe talk with @dradX - maybe we extend vm_disk object (type cd-rom) with some magic "use-for-cloud-init" label.

It would mean extra burden for enduser - he needs to know in advance which CD-ROM will be used for cloud-init ISO. But likely he already needs to know that anyway, and this only get more obvious.

**Comment by domendobnikar** [comment]
@justinc1 @ddemlow 
Cloud init creates an IDE_CDROM with cloud-init ISO attached, which caused some idempotence problems with the VM module.
The idempotence part is now fixed.
When user first runs the VM playbook with cloud init, the VM is created and cloud init ISO is attached on the created IDE_CDROM.
If the same playbook is ran, the module return no changes and there are no changes on the WEB UI either, any additional cloud init data is also ignored.
If user decides to eject the cloud init ISO, then the IDE_CDROM will automatically be removed the next time VM playbook is ran, since it is not specified (in the playbook) or used anymore.
User can also "override" cloud init ISO by using vm_disk module and assigning another IDE or attaching a different ISO to that specific disk slot. (This is in case user wants to keep the IDE_CDROM with a different ISO)
