### ISSUE TITLE
`SC_URL` should be `SC_HOST` in documentation

### ISSUE THREAD

**Issue by shoriminimoe** [ScaleComputing/HyperCoreAnsibleCollection#57]
The docs mention `SC_URL` in many places when I believe it should be `SC_HOST`

https://github.com/ScaleComputing/HyperCoreAnsibleCollection/blob/aa5de2e30f250b70a0046fb97c06630406bee358/plugins/doc_fragments/cluster_instance.py#L23

**Comment by justinc1** [comment]
Documentation is auto-generated from code, and PR will update the code. On next release (or maybe earlier) we need to also update documentation.
