### ISSUE TITLE
integration test snapshot_schedule will fail if no snapshot schedules exist

### ISSUE THREAD

**Issue by ddemlow** [ScaleComputing/HyperCoreAnsibleCollection#59]
by default there are no snapshot schedules created until either a user creates one manually, OR a default replication schedule is created by replicating a VM.  

so on a fresh cluster - this test fails.  should probably create one if one doesn't exist

https://github.com/ScaleComputing/HyperCoreAnsibleCollection/blob/main/tests/integration/targets/snapshot_schedule/tasks/main.yml

**Comment by justinc1** [comment]
OK, we need to create in related integration tests some snapshot schedule if there is none.
