### ISSUE TITLE
socket.timeout: The read operation timed out when API response takes too long - impacting integration test

### ISSUE THREAD

**Issue by ddemlow** [ScaleComputing/HyperCoreAnsibleCollection#60]
seen randomly on "busy" clusters with more VM's ... most common on import/export operations which have some additional steps (network access to smb server)

from internal scaleUI.log
2022/12/13 15:21:59.907 info  rest.js:87                          | Path: /VirDomainSnapshotSchedule, Method: GET, Request Body: {}, Status: 200 Response: 0.819s
2022/12/13 15:22:11.625 info  rest.js:87                          | Path: /VirDomain/37fa1108-126e-4d71-a981-5076b80c1819/export, Method: POST, Request Body: {"target":{"pathURI":"smb://remotedc;administrator:Scale2010@10.100.18.186/data/integration-test-vm-export","definitionFileName":"my_file.xml"},"template":{}}, Status: 200 Response: **11.711s**

resulting in this failure from ansible perspective (the export did actually happen)

TASK [vm_export : Export XLAB-export-test-integration to SMB] *****************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: socket.timeout: The read operation timed out
fatal: [testhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 121, in <module>\n  File \"<stdin>\", line 113, in _ansiballz_main\n  File \"<stdin>\", line 61, in invoke_module\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_scale_computing.hypercore.vm_export_payload_mp5b3alq/ansible_scale_computing.hypercore.vm_export_payload.zip/ansible_collections/scale_computing/hypercore/plugins/modules/vm_export.py\", line 165, in <module>\n  File \"/tmp/ansible_scale_computing.hypercore.vm_export_payload_mp5b3alq/ansible_scale_computing.hypercore.vm_export_payload.zip/ansible_collections/scale_computing/hypercore/plugins/modules/vm_export.py\", line 158, in main\n  File \"/tmp/ansible_scale_computing.hypercore.vm_export_payload_mp5b3alq/ansible_scale_computing.hypercore.vm_export_payload.zip/ansible_collections/scale_computing/hypercore/plugins/modules/vm_export.py\", line 98, in run\n  File \"/tmp/ansible_scale_computing.hypercore.vm_export_payload_mp5b3alq/ansible_scale_computing.hypercore.vm_export_payload.zip/ansible_collections/scale_computing/hypercore/plugins/module_utils/vm.py\", line 512, in export_vm\n  File \"/tmp/ansible_scale_computing.hypercore.vm_export_payload_mp5b3alq/ansible_scale_computing.hypercore.vm_export_payload.zip/ansible_collections/scale_computing/hypercore/plugins/module_utils/rest_client.py\", line 53, in create_record\n  File \"/tmp/ansible_scale_computing.hypercore.vm_export_payload_mp5b3alq/ansible_scale_computing.hypercore.vm_export_payload.zip/ansible_collections/scale_computing/hypercore/plugins/module_utils/client.py\", line 143, in post\n  File \"/tmp/ansible_scale_computing.hypercore.vm_export_payload_mp5b3alq/ansible_scale_computing.hypercore.vm_export_payload.zip/ansible_collections/scale_computing/hypercore/plugins/module_utils/client.py\", line 134, in request\n  File \"/tmp/ansible_scale_computing.hypercore.vm_export_payload_mp5b3alq/ansible_scale_computing.hypercore.vm_export_payload.zip/ansible_collections/scale_computing/hypercore/plugins/module_utils/client.py\", line 84, in _request\n  File \"/tmp/ansible_scale_computing.hypercore.vm_export_payload_mp5b3alq/ansible_scale_computing.hypercore.vm_export_payload.zip/ansible/module_utils/urls.py\", line 1446, in open\n  File \"/usr/lib/python3.8/urllib/request.py\", line 222, in urlopen\n    return opener.open(url, data, timeout)\n  File \"/usr/lib/python3.8/urllib/request.py\", line 525, in open\n    response = self._open(req, data)\n  File \"/usr/lib/python3.8/urllib/request.py\", line 542, in _open\n    result = self._call_chain(self.handle_open, protocol, protocol +\n  File \"/usr/lib/python3.8/urllib/request.py\", line 502, in _call_chain\n    result = func(*args)\n  File \"/tmp/ansible_scale_computing.hypercore.vm_export_payload_mp5b3alq/ansible_scale_computing.hypercore.vm_export_payload.zip/ansible/module_utils/urls.py\", line 582, in https_open\n  File \"/usr/lib/python3.8/urllib/request.py\", line 1358, in do_open\n    r = h.getresponse()\n  File \"/usr/lib/python3.8/http/client.py\", line 1348, in getresponse\n    response.begin()\n  File \"/usr/lib/python3.8/http/client.py\", line 316, in begin\n    version, status, reason = self._read_status()\n  File \"/usr/lib/python3.8/http/client.py\", line 277, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n  File \"/usr/lib/python3.8/socket.py\", line 669, in readinto\n    return self._sock.recv_into(b)\n  File \"/usr/lib/python3.8/ssl.py\", line 1241, in recv_into\n    return self.read(nbytes, buffer)\n  File \"/usr/lib/python3.8/ssl.py\", line 1099, in read\n    return self._sslobj.read(len, buffer)\nsocket.timeout: The read operation timed out\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP ********************************************************************************************************************************************************************************
testhost                   : ok=5    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

NOTICE: To resume at this test target, use the option: --start-at vm_export
NOTICE: To resume after this test target, use the option: --start-at vm_git_issues
ERROR: Command "ansible-playbook vm_export-7k9oh07a.yml -i inventory" returned exit status 2.
[15:27](https://scalecomputing.slack.com/archives/C03NDHAJWEA/p1670963276676079)

this time it worked  … 7.9 seconds (again from scaleUI.log)
2/12/13 15:27:17.020 info  rest.js:87                          | Path: /VirDomain/10baeb4f-aa6f-49ef-a09d-05421cb1f8ea/export, Method: POST, Request Body: {"target":{"pathURI":"smb://remotedc;administrator:Scale2010@10.100.18.186/data/integration-test-vm-export","definitionFileName":"my_file.xml"},"template":{}}, Status: 200 Response: 7.903s

**Comment by justinc1** [comment]
As temporal wokraround, `cluster_instance.timeout` (environ `SC_TIMEOUT`) can be set to something higher than default 10 sec.

For future, we could use higher timeout for specific REST operations.

**Comment by ddemlow** [comment]
is this what you are proposing? this does not seem to be having any impact on that 10 second threshold

    - name: Export XLAB-import-test-integration to SMB
      scale_computing.hypercore.vm_export:
        cluster_instance:
          timeout: 120
        vm_name: XLAB-import-test-integration
        smb:
          server: "{{ smb_server }}"
          path: "{{ smb_share }}/integration-test-vm-import"
          username: "{{ smb_username }}"
          password: "{{ smb_password }}"
      register: output
    - ansible.builtin.assert:
        that:
          - output is changed
          - output.msg == "Virtual machine - XLAB-import-test-integration - export complete."

**Comment by ddemlow** [comment]
also tried in this stand-alone playbook with same results 

- name: test export
  hosts: edge # use ansible-playbook -l group to limit application to specific groups
  connection: local
#  strategy: host_pinned # free  #allows each cluster to start next task before all clusters have finished current task
  environment:  #if set here - hypercore modules will automatically use this for each remote cluster - avoiding need to specify cluster_instance for each test
    SC_HOST: "https://{{ inventory_hostname }}"
    SC_USERNAME: "{{ scale_admin_user }}"
    SC_PASSWORD: "{{ scale_admin_pass }}"

  tasks:
    - name: Export XLAB-export-test-integration to SMB
      scale_computing.hypercore.vm_export:
        cluster_instance:
          timeout: 20
        vm_name: XLAB-export-test-integration
        smb:
          server: "10.100.20.175"
          path: "/data"
          username: "remotedc;administrator"
          password: "Scale2010"
          file_name: my_file.xml
      register: output
    - ansible.builtin.assert:
        that:
          - output is changed
          - output.msg == "Virtual machine - XLAB-export-test-integration - export complete."

**Comment by justinc1** [comment]
@ddemlow True, the timeout option is not correctly implemented. Will be fixed.
